name: Run Cookiecutter to generate project structure

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Enter the project name'
        required: true
      repo_owner_full_name:
        description: 'Enter the owner full name'
        required: true
      repo_owner_email:
        description: 'Enter the owner email'
        required: true
      description:
        description: 'Enter the project description'
        required: true

permissions:
  contents: write  # Donner l'accès en écriture pour cloner/pusher sur le dépôt privé
  issues: write    # Si vous devez gérer les issues dans un dépôt privé
  pull-requests: write  # Si vous devez gérer des pull requests

jobs:
  generate_project:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt de template dans le sous-dossier "template"
      - name: Checkout template repository
        uses: actions/checkout@v4
        with:
          repository: RashidOrga/pyth_template
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
          path: template  # Cloner le template dans un sous-dossier "template"
      
      # Étape 2 : Cloner le dépôt principal dans un sous-dossier "main-repo"
      - name: Checkout main repository  # Cloner le dépôt principal dans "main-repo"
        uses: actions/checkout@v4
        with:
          path: main-repo  # Clonage du dépôt principal dans "main-repo"
  
      # Étape 3 : Installer Cookiecutter
      - name: Install Cookiecutter
        run: pip install cookiecutter
  
      # Étape 4 : Exécuter Cookiecutter pour générer la structure du projet dans le dépôt principal
      - name: Run Cookiecutter to generate project structure
        run: |
          template_path=$(realpath template)
          cd main-repo
          cookiecutter --no-input --verbose $template_path
  
      # Étape 5 : Commit et Push des changements (dans le dépôt principal)
      - name: Commit and Push generated project
        run: |
          cd main-repo
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Generate project using cookiecutter template"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}